import {
  Task,
  TaskCategory,
  TaskDifficulty,
  TaskFrequency,
  TaskTargetUnit,
  TaskVerificationType,
} from '../tasks/schemas/task.schema';

export const taskSeedData = [
  {
    code: 'FIRST_STEPS',
    title: 'Bước chân đầu tiên',
    description: 'Ra ngoài và hoàn thành quãng đường đi bộ 500m.',
    category: TaskCategory.WALK,
    verificationType: TaskVerificationType.GPS_DISTANCE,
    frequency: TaskFrequency.DAILY,
    emoji: '🚶',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 20,
    rewardLp: 5,
    unlockMinutes: 5,
    targetValue: 500,
    targetUnit: TaskTargetUnit.METER,
    estimatedMinutes: 8,
    instructions: [
      'Bật định vị trên thiết bị.',
      'Đi bộ ngoài trời đủ 500 mét.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'MORNING_WALK',
    title: 'Đi dạo buổi sáng',
    description:
      'Bắt đầu ngày mới bằng một buổi đi bộ nhẹ nhàng trước 9 giờ sáng.',
    category: TaskCategory.WALK,
    verificationType: TaskVerificationType.GPS_DISTANCE,
    frequency: TaskFrequency.DAILY,
    emoji: '🚶',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 50,
    rewardLp: 10,
    unlockMinutes: 15,
    targetValue: 2000,
    targetUnit: TaskTargetUnit.METER,
    estimatedMinutes: 25,
    instructions: [
      'Bật định vị trên thiết bị.',
      'Đi bộ ngoài trời đủ 2000 mét.',
    ],
    startTime: '05:00',
    endTime: '09:00',
    active: true,
  },
  {
    code: 'LUNCH_BREAK_WALK',
    title: 'Nghỉ trưa năng động',
    description: 'Rời bàn làm việc và đi bộ 1km trong thời gian nghỉ trưa.',
    category: TaskCategory.WALK,
    verificationType: TaskVerificationType.GPS_DISTANCE,
    frequency: TaskFrequency.DAILY,
    emoji: '🚶',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 30,
    rewardLp: 7,
    unlockMinutes: 10,
    targetValue: 1000,
    targetUnit: TaskTargetUnit.METER,
    estimatedMinutes: 13,
    instructions: [
      'Bật định vị trên thiết bị.',
      'Đi bộ ngoài trời đủ 1000 mét.',
    ],
    startTime: '11:00',
    endTime: '14:00',
    active: true,
  },
  {
    code: 'GREEN_JOURNEY',
    title: 'Chuyến đi xanh',
    description: 'Hoàn thành quãng đường đi bộ 3km ngoài trời.',
    category: TaskCategory.WALK,
    verificationType: TaskVerificationType.GPS_DISTANCE,
    frequency: TaskFrequency.ANYTIME,
    emoji: '🌳',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 75,
    rewardLp: 15,
    unlockMinutes: 20,
    targetValue: 3000,
    targetUnit: TaskTargetUnit.METER,
    estimatedMinutes: 40,
    instructions: [
      'Bật định vị trên thiết bị.',
      'Đi bộ ngoài trời đủ 3000 mét.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'WEEKEND_EXPLORER',
    title: 'Nhà thám hiểm cuối tuần',
    description: 'Đi bộ 5km ngoài trời trong một lần.',
    category: TaskCategory.WALK,
    verificationType: TaskVerificationType.GPS_DISTANCE,
    frequency: TaskFrequency.WEEKLY,
    emoji: '🧭',
    difficulty: TaskDifficulty.HARD,
    rewardXp: 150,
    rewardLp: 35,
    unlockMinutes: 30,
    targetValue: 5000,
    targetUnit: TaskTargetUnit.METER,
    estimatedMinutes: 75,
    instructions: [
      'Bật định vị trên thiết bị.',
      'Đi bộ ngoài trời đủ 5000 mét trong một lần.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },

  //Photo tasks
  {
    code: 'FIND_GREEN',
    title: 'Tìm màu xanh',
    description: 'Tìm và chụp một cây xanh thật ở ngoài trời.',
    category: TaskCategory.PHOTO,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Plant', 'Tree', 'Leaf'],
    frequency: TaskFrequency.DAILY,
    emoji: '🌿',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 25,
    rewardLp: 5,
    unlockMinutes: 5,
    targetValue: 1,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 5,
    instructions: [
      'Tìm một cây hoặc thực vật ngoài trời.',
      'Chụp ảnh rõ nét bằng camera của TouchGrass.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },

  {
    code: 'FLOWER_HUNTER',
    title: 'Người săn hoa',
    description: 'Tìm và chụp một bông hoa thật trong môi trường tự nhiên.',
    category: TaskCategory.PHOTO,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Flower', 'Blossom', 'Plant'],
    frequency: TaskFrequency.DAILY,
    emoji: '🌸',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 30,
    rewardLp: 7,
    unlockMinutes: 10,
    targetValue: 1,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 10,
    instructions: [
      'Mở camera trực tiếp trong TouchGrass.',
      'Chụp rõ một bông hoa thật.',
      'Không sử dụng ảnh từ thư viện.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'LOOK_AT_THE_SKY',
    title: 'Nhìn lên bầu trời',
    description: 'Dành một phút quan sát rồi chụp bầu trời hoặc đám mây.',
    category: TaskCategory.PHOTO,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Sky', 'Cloud'],
    frequency: TaskFrequency.DAILY,
    emoji: '☁️',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 25,
    rewardLp: 5,
    unlockMinutes: 5,
    targetValue: 1,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 5,
    instructions: [
      'Mở camera trực tiếp trong TouchGrass.',
      'Hướng camera lên bầu trời hoặc đám mây.',
      'Không sử dụng ảnh từ thư viện.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'FIND_WATER',
    title: 'Tìm nguồn nước',
    description: 'Chụp một nguồn nước tự nhiên như hồ, sông, suối hoặc mưa.',
    category: TaskCategory.PHOTO,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Water', 'Lake', 'River', 'Rain'],
    frequency: TaskFrequency.WEEKLY,
    emoji: '💧',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 50,
    rewardLp: 12,
    unlockMinutes: 15,
    targetValue: 1,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 15,
    instructions: [
      'Mở camera trực tiếp trong TouchGrass.',
      'Chụp rõ nguồn nước tự nhiên.',
      'Không sử dụng ảnh từ thư viện.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'LEAF_COLLECTION',
    title: 'Bộ sưu tập lá',
    description: 'Chụp ba chiếc lá có hình dạng khác nhau.',
    category: TaskCategory.PHOTO,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Leaf', 'Plant'],
    frequency: TaskFrequency.WEEKLY,
    emoji: '🍃',
    difficulty: TaskDifficulty.HARD,
    rewardXp: 100,
    rewardLp: 25,
    unlockMinutes: 25,
    targetValue: 3,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 25,
    instructions: [
      'Mở camera trực tiếp trong TouchGrass.',
      'Chụp lần lượt ba chiếc lá.',
      'Không sử dụng ảnh từ thư viện.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },

  {
    code: 'QUICK_EYE_BREAK',
    title: 'Nghỉ mắt nhanh',
    description: 'Đặt điện thoại xuống và nghỉ mắt trong 10 phút.',
    category: TaskCategory.OFFLINE,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.DAILY,
    emoji: '😌',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 20,
    rewardLp: 5,
    unlockMinutes: 5,
    targetValue: 10,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 10,
    instructions: [
      'Bắt đầu bộ đếm thời gian trong TouchGrass.',
      'Tắt màn hình và không sử dụng điện thoại trong 10 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'SCREEN_FREE_MEAL',
    title: 'Bữa ăn không màn hình',
    description:
      'Không sử dụng điện thoại trong một bữa ăn kéo dài ít nhất 20 phút.',
    category: TaskCategory.OFFLINE,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.DAILY,
    emoji: '🍽️',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 40,
    rewardLp: 10,
    unlockMinutes: 10,
    targetValue: 20,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 20,
    instructions: [
      'Bắt đầu bộ đếm trước bữa ăn.',
      'Tắt màn hình và không sử dụng điện thoại trong 20 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'FOCUS_SESSION',
    title: 'Phiên tập trung',
    description:
      'Đặt điện thoại sang một bên và tập trung học tập hoặc làm việc trong 25 phút.',
    category: TaskCategory.OFFLINE,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.DAILY,
    emoji: '🎯',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 50,
    rewardLp: 12,
    unlockMinutes: 15,
    targetValue: 25,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 25,
    instructions: [
      'Bắt đầu phiên tập trung trong TouchGrass.',
      'Tắt màn hình và không sử dụng điện thoại trong 25 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'THIRTY_MINUTE_BREAK',
    title: 'Khoảng lặng 30 phút',
    description: 'Không sử dụng điện thoại trong 30 phút liên tục.',
    category: TaskCategory.OFFLINE,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.DAILY,
    emoji: '🤫',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 65,
    rewardLp: 15,
    unlockMinutes: 20,
    targetValue: 30,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 30,
    instructions: [
      'Bắt đầu bộ đếm thời gian.',
      'Tắt màn hình và không sử dụng điện thoại trong 30 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'ONE_HOUR_OFFLINE',
    title: 'Một giờ tự do',
    description: 'Dành trọn một giờ cho cuộc sống bên ngoài màn hình.',
    category: TaskCategory.OFFLINE,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.WEEKLY,
    emoji: '📵',
    difficulty: TaskDifficulty.HARD,
    rewardXp: 120,
    rewardLp: 30,
    unlockMinutes: 30,
    targetValue: 60,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 60,
    instructions: [
      'Bắt đầu phiên ngoại tuyến trong TouchGrass.',
      'Tắt màn hình và không sử dụng điện thoại trong 60 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'BREATHE_AND_RELAX',
    title: 'Hít thở và thư giãn',
    description:
      'Ngồi thoải mái và thực hiện bài tập hít thở chậm trong 5 phút.',
    category: TaskCategory.WELLNESS,
    verificationType: TaskVerificationType.MANUAL_CHECKIN,
    frequency: TaskFrequency.DAILY,
    emoji: '🧘',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 15,
    rewardLp: 4,
    unlockMinutes: 5,
    targetValue: 5,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 5,
    instructions: [
      'Ngồi ở một vị trí thoải mái.',
      'Hít thở chậm và đều trong 5 phút.',
      'Xác nhận sau khi hoàn thành.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'GENTLE_STRETCH',
    title: 'Giãn cơ nhẹ nhàng',
    description:
      'Rời khỏi ghế và thực hiện các động tác giãn cơ nhẹ trong 5 phút.',
    category: TaskCategory.WELLNESS,
    verificationType: TaskVerificationType.MANUAL_CHECKIN,
    frequency: TaskFrequency.DAILY,
    emoji: '🤸',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 20,
    rewardLp: 5,
    unlockMinutes: 5,
    targetValue: 5,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 5,
    instructions: [
      'Đứng dậy khỏi ghế.',
      'Thực hiện các động tác giãn cơ nhẹ trong 5 phút.',
      'Xác nhận sau khi hoàn thành.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'CLEAN_YOUR_DESK',
    title: 'Dọn dẹp góc học tập',
    description: 'Dành 10 phút để sắp xếp bàn học hoặc không gian làm việc.',
    category: TaskCategory.WELLNESS,
    verificationType: TaskVerificationType.MANUAL_CHECKIN,
    frequency: TaskFrequency.DAILY,
    emoji: '🧹',
    difficulty: TaskDifficulty.EASY,
    rewardXp: 25,
    rewardLp: 6,
    unlockMinutes: 10,
    targetValue: 10,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 10,
    instructions: [
      'Dọn các vật dụng không cần thiết.',
      'Sắp xếp bàn học hoặc bàn làm việc.',
      'Xác nhận sau khi hoàn thành.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'READ_A_BOOK',
    title: 'Đọc sách thay màn hình',
    description: 'Đọc sách giấy trong 20 phút mà không sử dụng điện thoại.',
    category: TaskCategory.WELLNESS,
    verificationType: TaskVerificationType.SCREEN_OFF_TIMER,
    frequency: TaskFrequency.DAILY,
    emoji: '📖',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 45,
    rewardLp: 10,
    unlockMinutes: 15,
    targetValue: 20,
    targetUnit: TaskTargetUnit.MINUTE,
    estimatedMinutes: 20,
    instructions: [
      'Chuẩn bị một cuốn sách giấy.',
      'Bắt đầu bộ đếm thời gian.',
      'Tắt màn hình và đọc sách trong 20 phút.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
  {
    code: 'CARE_FOR_A_PLANT',
    title: 'Chăm sóc không gian xanh',
    description: 'Tưới cây hoặc chăm sóc cây trong nhà hay ngoài trời.',
    category: TaskCategory.WELLNESS,
    verificationType: TaskVerificationType.PHOTO_AI,
    verificationLabels: ['Plant', 'Tree', 'Leaf'],
    frequency: TaskFrequency.WEEKLY,
    emoji: '🪴',
    difficulty: TaskDifficulty.MEDIUM,
    rewardXp: 40,
    rewardLp: 10,
    unlockMinutes: 15,
    targetValue: 1,
    targetUnit: TaskTargetUnit.PHOTO,
    estimatedMinutes: 15,
    instructions: [
      'Chăm sóc hoặc tưới một cây xanh.',
      'Mở camera trực tiếp trong TouchGrass.',
      'Chụp ảnh rõ cây đã chăm sóc.',
      'Không sử dụng ảnh từ thư viện.',
    ],
    startTime: null,
    endTime: null,
    active: true,
  },
] satisfies Task[];
